# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a10848cd47f02559081f7805103e3887107b79de69936ffd18370c9f441b06fea6c05de638404be2fe3520dbad6fac78483fe72117889a32f3c9949bb6c79a9

test:
  secret_key_base: 2eff3be9d59150179637b366e13d302480aff982f7cc124abc231d999f8b6acf391aa65b7c2938adc631f0c2a84d6cb37c22b64cfd5bcd223cf398408fea0a05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
